services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ctmds:/app/ctmds  # Hot reload
      - ./data:/app/data  # Database

volumes:
  ctmds:
  data:
