name: Build Docker image

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dockerpaps/ctmds

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: $(git rev-parse --short "$GITHUB_SHA")
          labels: ${{ steps.meta.outputs.labels }}
