name: build-docker-image

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pre-tests:
    uses: ./pre-tests.yml
  tests:
    uses: ./tests.yml
  build:
    name: Build Docker image
    needs: [tests, pre-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dockerpaps/ctmds

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
