name: ci

jobs:
  pre-tests:
    uses: ./.github/workflows/pre-tests.yaml
  tests:
    uses: ./.github/workflows/tests.yaml
  build:
    uses: ./.github/workflows/build.yaml
  publish:
    uses: ./.github/workflows/publish.yaml
