name: ci

on:
  push:

jobs:
  pre-tests:
    uses: ./.github/workflows/pre-tests.yaml
  tests:
    uses: ./.github/workflows/tests.yaml
  build:
    uses: ./.github/workflows/build.yaml
    needs: [pre-tests, tests]
  publish:
    uses: ./.github/workflows/publish.yaml
