name: Publish Docker image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dockerpaps/ctmds

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $(git rev-parse --short HEAD)
          labels: ${{ steps.meta.outputs.labels }}
