name: tests

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  functional-tests:
    name: Functional tests
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        uses: ./.github/actions/test/
